# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NEUBlogIdea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Purchases'


  # Pods for NEUBlogIdea

  target 'NEUBlogIdeaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NEUBlogIdeaUITests' do
    # Pods for testing
  end

end
